project:
  type: website
  output-dir: docs

website:
  title: "Dissertation Notes and Writing"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: background.qmd
        text: Background
      - href: specificaims.qmd
        text: "Specific Aims"
      - href: aim1.qmd
        text: "Aim 1"
      - href: aim2.qmd
        text: "Aim 2"
      - href: aim3.qmd
        text: "Aim 3"
      - href: presentations.qmd
        text: "Presentations"

format:
  html:
    theme: solar
    css: styles.css
    toc: true



