---
execute: 
  echo: false
  warning: false
  message: false
format: 
  html:
    toc: true
    self-contained: true
    lightbox: true
    link-external-newwindow: true
  pdf:
    number-sections: false
bibliography: assets/references/proposal.bib
---


# 1. Specific Aims

**Aim 1. Identify and model correlates of protection against influenza in animal models.** Animal models are frequently used in vaccine design and selection. The standard human HAI 50% protective titer (50%PT) of 1:40 is commonly used as an endpoint in these animal models under the assumption that the 50%PTs are equivalent across species. However, there have not been studies to confirm these equivalencies. We will conduct correlates of protection analyses in pre-immune murine and ferret challenge models to assess

**Aim 2. Evaluate benefit of high-dose influenza vaccination by estimating and comparing Fluzone vaccine efficacies in age- and dose-based groups.** Older adults are now recommended to receive enhanced influenza vaccines, like those with a higher dose, to combat immunosenescence and influenza vulnerabilities. However, the use of these enhanced vaccines have not been assessed in extended cohort studies to determine their true benefit. Using the UGAFluVac immunogenicity data, we will estimate vaccine efficacies in younger adults receiving standard-dose Fluzone vaccines, older adults receiving standard-dose Fluzone vaccines, and older adults receiving high-dose Fluzone vaccines. Using a pre-defined model, we will map HAI titers to protection probabilities and use pre- and post-vaccination protection probabilities to estimate vaccine efficacies. We will then use contrasts to assess the benefit of older adults being given high-dose vaccines. 

**Aim 3. Quantify the impact of antigenic distance between vaccine and circulating influenza strains on vaccine effectiveness.** 