---
title: "Aim 3 Analysis Plan"
author: "Savannah L. Miller"
date-modified: last-modified
bibliography: ../../assets/references/proposal.bib
---

We will collect and combine data from previously published articles and reports for this aim. 

# Preliminary results 

We have created a simple DAG (@fig-dag) describing what we believe are the most important variables on the causal pathway between vaccine/circulating strain antigenic distance (AD) and vaccine effectiveness (VE). In this framework, we believe that the circulating strain (CS) and vaccine strain (VS) will each have direct effects on population VE, as well as leading to the antigenic distance result. We also assume that pre-season immunity (PT), as indicated by HAI titer, will impact VE, although we will not have this information as part of our data set. The vaccine strain in the previous season's vaccine (PVS) may also impact VE, as described in the _antigenic distance hypothesis_ [@skowronski2017]. Vaccine uptake (VU) may also impact VE through changes in direct and indirect vaccination effects [@eichner2017]. Demographic factors (D) such as age, race, etc. influence VE both directly and indirectly through (VU). We plan to collect data on CS, VS, PVS, and VE in all cases, and will also collect and examine impacts of VU and D as data are available. AD will be calculated using VS and CS. 


```{r}
#| message: false
#| echo: false
#| label: fig-dag
#| fig-cap: "Relevant exposures, outcomes, and covariates on the causal pathway between antigenic distance (AD) and vaccine effectiveness (VE). Exposures (yellow) include AD, circulating influenza strain (CS), vaccine strain (VS), pre-season HAI titers (PT), previous year vaccine strain (PVS), and population vaccine uptake (VU). Demographics (D) is included as a covariate (orange). Our outcome (gray) of interest is VE."

library(dagitty)
library(ggdag)
library(NatParksPalettes)

dag <- dagitty::dagitty("
dag {
AD [exposure,pos=\"-0.830,0.001\"]
CS [exposure,pos=\"-1.742,0.507\"]
D [pos=\"-0.777,-0.410\"]
PT [exposure,pos=\"-1.519,-0.329\"]
PVS [exposure,pos=\"0.063,-0.981\"]
VE [outcome,pos=\"-1.742,-1.369\"]
VS [exposure,pos=\"1.355,-1.369\"]
VU [exposure,pos=\"-0.336,-0.722\"]
AD -> VE
CS -> AD
CS -> VE
D -> VE
D -> VU
PT -> VE
PVS -> VE
VS -> AD
VS -> VE
VU -> VE
}
")

tidy_dag <- 
  ggdag::tidy_dagitty(dag) |> 
  dplyr::mutate(Status = dplyr::case_when(
    name == "VE" ~ "Outcome",
    name == "D" ~ "Covariate",
    TRUE ~ "Exposure"
  ))  
  

# Optional: Plot or print summary
ggdag::ggdag(tidy_dag) +
  ggdag::geom_dag_point(ggplot2::aes(color = Status)) +
  ggdag::geom_dag_text() +
  ggdag::theme_dag() +
  NatParksPalettes::scale_color_natparks_d("Cuyahoga")

```


# Proposed studies

We will calculate VE using multiple methods, including _p_epitope_ distance [@gupta2006; @pan16], Grantham distance, 


We will use Bayesian mixed-effects meta-regression to examine the effect of our predictors on the VE outcome. 

$$
\begin{aligned}
\hat\theta_k &\sim \mathcal{N}(\theta_k,\sigma^2_k)\\
\theta_k &\sim \mathcal{N}(\mu_k, \tau^2), \space \space \mu_k = \beta_0 + \sum_{j=1}^p\beta_jx_{j,k} + b^{(s)}_{s[k]} + b^{(t)}_{t[k]} + b^{(x_1t)}_{x_1,t}\\
b_s^{(s)} &\sim \mathcal{N}(0, \sigma^2_s)\\
b_t^{(t)} &\sim \mathcal{N}(0, \sigma^2_t)\\
b_t^{(x1t)} &\sim \mathcal{N}(0, \sigma^2_{x_1t})\\
\end{aligned}
$$

Term | Interpretation
-|---
$\hat\theta_k$|Observed estimate from study $k$
$\theta_k$|True underlying effect for study $k$
$\sigma^2_k$| Known sampling variance for $\hat\theta_k$
$\beta_0$|Fixed intercept
$\beta_j$|Fixed slopes for predictors $x_j, j \ge2$
$b_s^{(s)}$|
$b_t^{(t)}$|
$b_t^{(x_1t)}$|


# Expected outcomes


